language: python

python:
  - "3.4"
  - "3.5"

sudo: required

install:
  - pip install coveralls

script:
  - coverage run --source=statstuff setup.py test && coverage report

after_success:
  coveralls