language: python

python:
  - "3.4"
  - "3.5"

sudo: required

install:
  - pip install coveralls

script:
  - coverage run setup.py test && coverage report --omit=documentation

after_success:
  - coveralls