language: python

python:
  - "3.4"
  - "3.5"

sudo: required

install:
  - pip install coveralls

script:
  - coverage run setup.py test && coverage report --omit=/home/travis/virtualenv/python3.5.2/lib/python3.5

after_success:
  - coveralls