language: python

python:
  - "3.4"
  - "3.5"

sudo: required

install:
  - pip install pytest pytest-cov
  - pip install coveralls

script:
  - py.test --cov=statstuff

after_success:
    - if [[ $ENV == python=3.5* ]]; then
          coveralls;
      fi